package com.inn.cafe.constants;

public class CafeConstants {
    public static final String SOMETHING_WENT_WRONG = "Something Went Wrong.";
    public static final String INVALID_REQUEST = "Invalid request.";
    public static final String USER_ALREADY_EXISTS = "User already exists!. Please try with different email.";
    public static final String USER_INSERTED = "User inserted.";
    public static final String PASSWORD_UPDATED_SUCCESSFULLY = "Password updated successfully!";
    public static final String ONLY_ADMIN_CAN_CHANGE_STATUS_OF_USER = "Only admin can change status of user.";
    public static final String USER_DOESNT_EXISTS = "User does not exists in database!";
    public static final String USER_STATUS_CHANGED_SUCCESSFULLY = "User status changed successfully!";
    public static final String CURRENT_TOKEN_BEAR_BY_ADMIN = "Current token is bear by admin";
    public static final String OLD_AND_NEW_PASSWORDS_SEEMS_SIMILAR_PLEASE_TRY_WITH_DIFFERENT_PASSWORD = "Sorry! old and new passwords seems similar. Please try with different password";
    public static final String UNAUTHORIZED_ACCESS="Unauthorized access";
    public static final String STORE_LOCATION="E:\\PROJECTS\\CFMS\\PDF GENERATED BY PROJECT";
}
